version: '3.9'

services:
  web:
    build: .
    container_name: blox_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - ./media:/app/media
    working_dir: /app

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped

volumes:
  postgres_data:
